// Mocks generated by Mockito 5.4.4 from annotations
// in clean_archi_project1/test/article_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_archi_project1/features/daily_news/data/data_sources/local/DAO/article_dao.dart'
    as _i5;
import 'package:clean_archi_project1/features/daily_news/data/data_sources/local/models/articleEntity.dart'
    as _i6;
import 'package:clean_archi_project1/features/daily_news/data/data_sources/remote/models/articleDto.dart'
    as _i4;
import 'package:clean_archi_project1/features/daily_news/data/data_sources/remote/news_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApiService extends _i1.Mock implements _i2.NewsApiService {
  MockNewsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ArticleDto>> getNewsArticle({
    String? apiKey,
    String? country,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewsArticle,
          [],
          {
            #apiKey: apiKey,
            #country: country,
            #category: category,
          },
        ),
        returnValue: _i3.Future<List<_i4.ArticleDto>>.value(<_i4.ArticleDto>[]),
      ) as _i3.Future<List<_i4.ArticleDto>>);
}

/// A class which mocks [ArticleDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleDao extends _i1.Mock implements _i5.ArticleDao {
  MockArticleDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insertArticle(_i6.ArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertArticle,
          [article],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.ArticleEntity>> getAllArticles() => (super.noSuchMethod(
        Invocation.method(
          #getAllArticles,
          [],
        ),
        returnValue: _i3.Stream<List<_i6.ArticleEntity>>.empty(),
      ) as _i3.Stream<List<_i6.ArticleEntity>>);

  @override
  _i3.Future<void> deleteArticle(_i6.ArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [article],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
